<a href="https://colab.research.google.com/github/phajavi/404-error/blob/main/image_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = tf.keras.datasets.fashion_mnist

In [4]:
(train_images,train_labels),(test_images,test_labels) = dataset.load_data()

In [7]:
print(f'''train_images_length: {len(train_images)}

      test_images_length: {len(test_images)}''')

train_images_length: 60000
      
      test_images_length: 10000


In [8]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [9]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [17]:
model = tf.keras.models.Sequential([

    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10)

    ])

In [18]:
model.compile(optimizer='adam',loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [20]:
model.fit(train_images,train_labels,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 3.8564 - accuracy: 0.6980
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.7132 - accuracy: 0.7421
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5704 - accuracy: 0.7969
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5419 - accuracy: 0.8048
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5073 - accuracy: 0.8200
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4919 - accuracy: 0.8293
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4835 - accuracy: 0.8324
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4789 - accuracy: 0.8352
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4713 - accuracy: 0.8365
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.465

In [24]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [31]:
prediction = probability_model.predict(test_images)

313/313 [==============================] - 1s 2ms/step


In [32]:
prediction[18]

array([3.7465000e-04, 6.0618532e-07, 1.2388526e-04, 1.8346474e-06,
       8.2981365e-05, 2.1061627e-03, 3.1299194e-04, 9.3210590e-05,
       9.9690342e-01, 1.2470606e-07], dtype=float32)

In [33]:
np.argmax(prediction[18])

8

In [36]:
test_labels[18]

8